### ISSUE TITLE
Add bubble sorting algorithm.

### ISSUE THREAD

**Issue by SrikanthYashaswi** [SrikanthYashaswi/visual-algos#4]

**Comment by icoder18** [comment]
Hi. I would like to take this up. Can you tell me which files need to be modified for this apart from adding bubbleSort.js ? I'll get started at the earliest.

**Comment by SrikanthYashaswi** [comment]
hey 
- checkout https://github.com/SrikanthYashaswi/visual-algos/blob/master/src/algorithms/SortingAlgorithmUtil.js
- thats the only place

**Comment by SrikanthYashaswi** [comment]
Hey,
Found an issue when sorting,
The `i` from `outer for-loop` is incrementing, which is leaving them unsorted.

**Comment by SrikanthYashaswi** [comment]
#9 fixed.
